name: Plugins manifest validation

on:
  push:
    paths:
      - "plugins.json"
  pull_request:
    paths:
      - "plugins.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r ./ci/envs/requirements-validator.txt

      - name: Test with pytest
        run: |
          pytest ./ci/src/validator.py
